catalog:
  "@modelcontextprotocol/sdk": "^1.12.1"
  "arktype": "^2.1.20"

catalogMode: "prefer"

onlyBuiltDependencies:
  - "@hurdlegroup/robotjs"
  - electron
  - esbuild
  - get-windows
  - mac-screen-capture-permissions
  - odiff-bin
  - sharp

packages:
  - examples/*
  - packages/*
