packages:
  - examples/*
  - packages/*

catalog:
  '@modelcontextprotocol/sdk': ^1.12.1
  '@total-typescript/tsconfig': ^1.0.4
  arktype: ^2.1.20
  fastmcp: ^2.2.2
  tsdown: 0.12.7
  typescript: ^5.8.3
  '@playwright/test': ^1.53.0
  '@types/node': ^24.0.1
  electron: ^33.4.11
  consola: ^3.4.2
  citty: ^0.1.6

catalogMode: prefer

onlyBuiltDependencies:
  - '@hurdlegroup/robotjs'
  - electron
  - esbuild
  - get-windows
  - mac-screen-capture-permissions
  - odiff-bin
  - sharp

saveCatalog: true
