name: Lint + Prettier
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: npm install
        run: npm ci --ignore-scripts
      - name: Run ESLint
        run: npx eslint . --max-warnings 0
      - name: Run Prettier
        run: npx prettier --check .
