name: Eslint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install modules
        run: npm install --production=false
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
      - name: Run Prettier
        run: npx prettier . --write
