name: Lint + Prettier
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: npm install 
        run: npm install --only=dev --ignore-scripts
      - name: Run ESLint
        run: npx eslint
      - name: Run Prettier
        run: npx prettier . --write
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
