on:
  push:
    branches:
      - main

name: Publish to NPM
jobs:
  bump_and_publish:
    steps: 
      - name: Automated Version Bump
        id: bump_version
        uses: phips28/gh-action-bump-version@master
        with:
          minor-wording: "MINOR"
          major-wording: "MAJOR"
          rc-wording: "ALPHA"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Publish
        runs-on: ubuntu-latest
        needs: bump_version
        uses: phips28/gh-action-bump-version@master
        steps:
          - uses: actions/checkout@v4
            with:
              ref: ${{ github.ref }}
          - uses: actions/setup-node@v3
            with:
              node-version: "20"
          - uses: JS-DevTools/npm-publish@v3
            with:
              token: ${{ secrets.NPM_AUTH_TOKEN }}
