on:
  push:
    branches:
      - main

name: Publish to NPM
jobs:
  bump_version:
    - name: Automated Version Bump
      uses: phips28/gh-action-bump-version@master
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        minor-wording: "MINOR"
        major-wording: "MAJOR"
        rc-wording: "ALPHA"
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: bump_version
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
