on:
  push:
    branches:
      - main

name: Publish to NPM
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - name: Publish
      uses: mikeal/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}