name: Publish @canary to NPM

permissions:
  contents: write
  pull-requests: write
  actions: read
  statuses: write

on:
  # So that we publish for every push to `main`, despite tests
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"
  workflow_dispatch:

jobs:
  publish-canary:
    name: Publish testdriverai@canary
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Version the package
        run: npm version --no-git-tag-version prerelease --preid=canary.$(git rev-parse --short HEAD)

      - name: Publish to canary and beta tags
        run: |
          npm publish --tag canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
