name: TestDriver.ai

permissions:
  contents: write
  pull-requests: write  
  actions: read
  statuses: write

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  gather-test-files:
    name: Gather Test Files
    runs-on: ubuntu-latest
    outputs:
      test_files: ${{ steps.test_list.outputs.files }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Find all test files
        id: test_list
        run: |
          FILES=$(ls ./testdriver/*.yaml)
          FILENAMES=$(basename -a $FILES)
          FILES_JSON=$(echo "$FILENAMES" | jq -R -s -c 'split("\n")[:-1]')
          echo "files=$FILES_JSON" >> $GITHUB_OUTPUT

  run-tests:
    name: Run Tests
    needs: gather-test-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows]
        test: ${{ fromJson(needs.gather-test-files.outputs.test_files) }}
      fail-fast: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run TestDriver
        id: testdriver
        uses: testdriverai/action@main
        with:
          os: ${{ contains(matrix.os, 'windows') && 'windows' || 'linux' }}
          version: "alpha"
          prerun: |
            exit
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          prompt: | 
            1. /run testdriver/${{ matrix.test }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: "3"
          TD_WEBSITE: "https://testdriver-sandbox.vercel.app"
          WEBSITE_URL: "example.com"

      - name: Write MDX to shared snippets dir
        run: |
          mkdir -p snippets
          FILE_NAME=$(basename "${{ matrix.test }}")
          TEST_FILE="testdriver/$FILE_NAME"
          DEST_FILE="snippets/${{ matrix.os }}-${FILE_NAME}.mdx"

          echo "<iframe src=\"${{ steps.testdriver.outputs.link }}\" />" > "$DEST_FILE"
          echo >> "$DEST_FILE"
          echo '```yaml' >> "$DEST_FILE"
          cat "$TEST_FILE" >> "$DEST_FILE"
          echo '```' >> "$DEST_FILE"

      - name: Upload snippets artifact
        uses: actions/upload-artifact@v4
        with:
          name: snippets-${{ matrix.os }}-${{ matrix.test }}
          path: snippets/
          retention-days: 1

  create-snippet-pr:
    name: Create Snippet PR
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download all snippets artifacts
        uses: actions/download-artifact@v4
        with:
          path: docs/snippets/tests
          pattern: snippets-*
          merge-multiple: true


      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update test snippets"
          branch: "update/test-snippets"
          title: "Update test snippets"
          body: |
            This PR includes the latest test snippet updates for all testdriver YAML files.
          labels: |
            automated
            test-snippet
          delete-branch: true
