name: Test – Environment Passthrough to VM

permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      SOME_SECRET: "secrets.SOME_SECRET"
      SOME_SCRIPT: |
        echo "SOME_SECRET: $SOME_SECRET"
      TD_API_KEY: ${{ secrets.TD_API_KEY }}

    steps:
      - uses: actions/checkout@v4
      - name: Re-export secrets to environment
        run: |
          echo "SOME_SECRET_2=${SOME_SECRET}" >> $GITHUB_ENV

      - name: Run TestDriver
        id: testdriver
        uses: testdriverai/action@main
        with:
          key: ${{ secrets.TD_API_KEY }}
          os: linux
          prerun: |
            echo "SOME_SECRET: $SOME_SECRET"
            echo "SOME_SECRET_2: $SOME_SECRET_2"
            echo "SOME_SCRIPT: $SOME_SCRIPT"
          prompt: |
            Page should contain "TestDriver.ai Sandbox"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SOME_SECRET: ${{ env.SOME_SECRET }}
          SOME_SCRIPT: ${{ env.SOME_SCRIPT }}
          TD_WEBSITE: "https://testdriver-sandbox.vercel.app"
