name: Test – Environment Passthrough to VM

permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      SOME_SECRET: "secrets.SOME_SECRET"
      SOME_SCRIPT: |
        echo "SOME_SECRET: $SOME_SECRET"

    steps:
      - uses: actions/checkout@v4

      - name: Re-export secrets to environment
        run: |
          echo "TD_SOME_SECRET=${SOME_SECRET}" >> $GITHUB_ENV
          echo "TD_SOME_SCRIPT=${SOME_SCRIPT}" >> $GITHUB_ENV

      - name: Verify secrets are exported to environment
        run: |
          printf 'SOME_SECRET:%s\n' "$SOME_SECRET"
          printf 'SOME_SCRIPT:%s\n' "$SOME_SCRIPT"
          printf 'TD_SOME_SECRET:%s\n' "$TD_SOME_SECRET"
          printf 'TD_SOME_SCRIPT:%s\n' "$TD_SOME_SCRIPT"

      - name: Run TestDriver
        id: testdriver
        uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          os: linux
          prerun: |
            echo "SOME_SECRET: $SOME_SECRET"
            echo "SOME_SCRIPT: $SOME_SCRIPT"
            echo "TD_SOME_SECRET: $TD_SOME_SECRET"
            echo "TD_SOME_SCRIPT: $TD_SOME_SCRIPT"
          prompt: |
            Page should contain "TestDriver.ai Sandbox"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SOME_SECRET: ${{ env.SOME_SECRET }}
          SOME_SCRIPT: ${{ env.SOME_SCRIPT }}
          TD_WEBSITE: "https://testdriver-sandbox.vercel.app"
