name: Test – Environment Passthrough to VM

permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      SOME_SECRET: "secrets.SOME_SECRET"
      SOME_SCRIPT: |
        echo "SOME_SECRET: $SOME_SECRET"
      TD_API_KEY: ${{ secrets.TD_API_KEY }}

    steps:
      - uses: actions/checkout@v4
      - name: Re-export secrets to environment
        run: |
          echo ${TD_API_KEY} > key
          echo "TD_API_KEY_2=$(cat key)" >> $GITHUB_ENV

      - name: Run TestDriver
        id: testdriver
        uses: testdriverai/action@main
        with:
          key: ${{ env.TD_API_KEY }}
          os: linux
          create-pr: false
          pr-branch: testdriver-results
          pr-title: "TestDriver QA Results"
          pr-test-filename: testdriver-results.yaml
          prerun: |
            printenv
          prompt: |
            1. check that Visual Studio Code is visible with the cdc_fifo folder open

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TD_VM: true
          TD_VM_RESOLUTION: 1280x1024
          TD_OVERLAY: true
          TD_ANALYTICS: false
          FORCE_COLOR: "3"
          TD_API_KEY: ${{ env.TD_API_KEY }}
          TD_SSH_SETUP_SCRIPT: ${{ env.TD_SSH_SETUP_SCRIPT }}
          TD_SSH_KEY: ${{ env.TD_SSH_KEY }}

      - name: Comment results on PR
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## 🧪 TestDriver QA Report

            **✅ Summary:**  
            ${{ steps.testdriver.outputs.summary || 'No summary available.' }}

            **🖼️ Markdown Report:**  
            ${{ steps.testdriver.outputs.markdown || 'No markdown report.' }}

            **🔗 Replay Link:**  
            [View Dashcam Replay](${{ steps.testdriver.outputs.link || '#' }})
