name: Test – Environment Passthrough to VM

permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      # Pretend we have a secret from GitHub
      SOME_SECRET: "secrets.SOME_SECRET"

    steps:
      - uses: actions/checkout@v4

      - name: Expose secrets to TestDriver with TD_* prefix
        run: |
          echo "TD_SOME_SECRET=${SOME_SECRET}" >> $GITHUB_ENV

      - name: Assert that all secrets are correctly in GitHub environment
        run: |
          if [[ "$SOME_SECRET" != "secrets.SOME_SECRET" ]]; then
            echo "SOME_SECRET is not set correctly: $SOME_SECRET"; exit 1;
          fi
          if [[ "$TD_SOME_SECRET" != "secrets.SOME_SECRET" ]]; then
            echo "TD_SOME_SECRET is not set correctly: $TD_SOME_SECRET"; exit 1;
          fi

      - name: Run TestDriver
        id: testdriver
        uses: testdriverai/action@main
        with:
          key: ${{ secrets.TESTDRIVER_API_KEY }}
          os: linux
          prerun: |
            Write-Host "# Asserting all values are empty in testdriverai/action's prerun"
            Write-Host "SOME_SECRET actual value: '$($env:SOME_SECRET)'"
            if ($env:SOME_SECRET) { Write-Host "SOME_SECRET should be empty"; }
            Write-Host "TD_SOME_SECRET actual value: '$($env:TD_SOME_SECRET)'"
            if ($env:TD_SOME_SECRET) { Write-Host "TD_SOME_SECRET should be empty"; }
          prompt: |
            Page should contain "TestDriver.ai Sandbox"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TD_WEBSITE: "https://testdriver-sandbox.vercel.app"
